services:
  app:
    image: mysociety/eir_analysis:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /workspaces/eir_analysis      
    volumes:
      - ./:/workspaces/eir_analysis/